// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250305225810_AddCartTables")]
    partial class AddCartTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 11",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 12",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 13",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 14",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 70000m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
